name: Compile and Test Java Api

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  java-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code from ${{ github.repository }}/${{ github.ref }}
        uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Update permissions
        working-directory: .
        run: chmod +x ./gradlew ./.github/scripts/*.sh
      - name: Check version
        working-directory: .
        run: ./.github/scripts/check_version.sh
      - name: Build and Test
        working-directory: .
        run: ./gradlew build test --info --stacktrace
